import type { Metadata } from "next";
import "./globals.css";
import { generalSans } from "./fonts";
import { ThemeProvider } from "../components/theme-provider";
import { SidebarProvider } from "../components/ui/sidebar";
import Appsidebar from "../components/Appsidebar";
import Header from "../components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${generalSans.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            
          <main className="w-screen">

            <div className="w-screen fixed top-0 left-0 z-40">
            <Header />
            </div>
            <div className="flex">
            <Appsidebar />
          <div className="px-4 flex-1 w-full">{children}</div>
          </div>
          </main>

          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
