import type { Metadata } from "next";
import "./globals.css";
import { generalSans } from "./fonts";
import { ThemeProvider } from "../components/theme-provider";
import { SidebarProvider } from "../components/ui/sidebar";
import Appsidebar from "../components/Appsidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${generalSans.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <Appsidebar />
          <main className="w-full">
            
          {children}
          </main>

          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
